# Intro to NumPy - Numerical Python

ndarray = n diensional array

In [1]:
import numpy as np

In [2]:
np1 = np.array([0, 1, 2, 3, 4])
np1

array([0, 1, 2, 3, 4])

In [3]:
np1.shape

(5,)

In [4]:
#range fxn
np2 = np.arange(10)
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np2.shape

(10,)

In [6]:
#step fxn
np3 = np.arange(0, 10, 2)
np3

array([0, 2, 4, 6, 8])

In [7]:
#zeroes
np4 = np.zeros(10)
np4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
#multidemensional zeroes
np5 = np.zeros((2, 10))
np5

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
#full
np6 = np.full((5,2), [10, 20])
np6

array([[10, 20],
       [10, 20],
       [10, 20],
       [10, 20],
       [10, 20]])

#Slicing numpy arrays

In [10]:
np21 = np.arange(10)
np21

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np21[1:5]

array([1, 2, 3, 4])

In [12]:
np21[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np21[0:11]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np21[0:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
np21[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [16]:
np21[:3]

array([0, 1, 2])

In [17]:
np21[-3:-1]

array([7, 8])

In [18]:
np21[0:6:2]

array([0, 2, 4])

In [19]:
np21[::2]

array([0, 2, 4, 6, 8])

In [20]:
np22 = np.arange(1, 13).reshape(3, 4)
np22

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
np22[2,3]

np.int64(12)

In [22]:
np22[0:1, 0:2]

array([[1, 2]])

In [23]:
np22[0:2, 0:2]

array([[1, 2],
       [5, 6]])

#universal fxns

In [24]:
np31 = np.arange(10)
np31

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.sqrt(np31)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [26]:
np.absolute(np31)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.exp(np31)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [28]:
np.max(np31)
np.min(np31)

np.int64(0)

In [29]:
#trigo log etc
np.sin(np31)
np.cos(np31)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [30]:
np.log(np31)

<ipython-input-30-3ea790368fb8>:1: RuntimeWarning: divide by zero encountered in log
  np.log(np31)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

#copy and view

In [31]:
np41 = np.arange(10)
np41

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np42 = np41.view()
np42

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
print(f"Orignal np41: {np41}")
print(f"View np42: {np42}")

Orignal np41: [0 1 2 3 4 5 6 7 8 9]
View np42: [0 1 2 3 4 5 6 7 8 9]


In [34]:
np41[0] = 100
print(f"changed np41: {np41}")
print(f"View np42: {np42}")

changed np41: [100   1   2   3   4   5   6   7   8   9]
View np42: [100   1   2   3   4   5   6   7   8   9]


In [35]:
#create a copy
np43 = np41.copy()
np43

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [36]:
print(f"Orignal np41: {np41}")
print(f"Copy np43: {np43}")

Orignal np41: [100   1   2   3   4   5   6   7   8   9]
Copy np43: [100   1   2   3   4   5   6   7   8   9]


In [37]:
np41[0] = 200
print(f"changed np41: {np41}")
print(f"Copy np43: {np43}")

changed np41: [200   1   2   3   4   5   6   7   8   9]
Copy np43: [100   1   2   3   4   5   6   7   8   9]


# Reshaping arrays

In [43]:
np51 = np.full(12, 10)
np51

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [44]:
np52 = np51.reshape(2, 6)
np52

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [41]:
np52 = np51.reshape(3, 5)
np52

ValueError: cannot reshape array of size 10 into shape (3,5)

In [45]:
np52 = np51.reshape(6, 2)
np52

array([[10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10]])

In [47]:
# reshape 3d
np53 = np51.reshape(3, 2, 2)
np53

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [48]:
np54 = np51.reshape(1, 2, 3, 2)
np54

array([[[[10, 10],
         [10, 10],
         [10, 10]],

        [[10, 10],
         [10, 10],
         [10, 10]]]])

# Iterating

In [50]:
np61 = np.arange(10)
np61

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
for x in np61:
  print(x)

0
1
2
3
4
5
6
7
8
9


In [52]:
np62 = np61.reshape(2, 5)
for x in np62:
  print(x)

[0 1 2 3 4]
[5 6 7 8 9]


In [53]:
for x in np62:
  for y in x:
    print(y)

0
1
2
3
4
5
6
7
8
9


In [54]:
# using np.nditer

for x in np.nditer(np62):
  print(x)

0
1
2
3
4
5
6
7
8
9


# Sorting

In [63]:
np71 = np.random.randint(0, 150, size =10) # Use np.random.rand to create a random array
np71

array([ 67, 112,  80,  54,  53, 126, 119,  37, 147,  53])

In [64]:
np72 = np.sort(np71)
np72

array([ 37,  53,  53,  54,  67,  80, 112, 119, 126, 147])

In [66]:
#alphabetical too
np73 = np.array(["sak", "adi", "bro", "nmt", "sis"])
np73

array(['sak', 'adi', 'bro', 'nmt', 'sis'], dtype='<U3')

In [67]:
# printing a sorted copy not the orignal
np.sort(np73)

array(['adi', 'bro', 'nmt', 'sak', 'sis'], dtype='<U3')